version: '3'

services:
  mosquitto:
    image: iegomez/mosquitto-go-auth
    depends_on:
      - nodejs
    volumes:
      - ./mosquitto.conf:/etc/mosquitto/mosquitto.conf
      - ./conf.d:/mosquitto/conf.d

    ports:
      - 1883:1883

  nodejs:
    build: ./node-backend
    ports:
      - 8000:8000
